/**
 * Seed data for top target accounts
 * These are based on public utility data (as of 2024)
 */

export const TARGET_ACCOUNTS_SEED = [
  // ── Top 10 Utilities (by CapEx) ────────────────────────────────────────────

  {
    company_name: "NextEra Energy",
    account_type: "utility",
    utility_category: "investor-owned",
    website: "nexteraenergy.com",
    service_territory: "Florida, Georgia, Connecticut",
    annual_capex: 18000000000,
    num_substations: 850,
    headquarters: "Juno Beach, FL",
    priority_score: 95,
    notes: "Largest U.S. utility by CapEx. Heavy focus on grid modernization.",
  },
  {
    company_name: "Duke Energy",
    account_type: "utility",
    utility_category: "investor-owned",
    website: "duke-energy.com",
    service_territory: "North Carolina, South Carolina, Florida, Ohio",
    annual_capex: 12000000000,
    num_substations: 720,
    headquarters: "Charlotte, NC",
    priority_score: 94,
    notes: "Major Southeast utility. Active capacity planning initiatives.",
  },
  {
    company_name: "American Electric Power (AEP)",
    account_type: "utility",
    utility_category: "investor-owned",
    website: "aep.com",
    service_territory: "11 states across Midwest and South",
    annual_capex: 11000000000,
    num_substations: 680,
    headquarters: "Columbus, OH",
    priority_score: 93,
    notes: "Large interconnection queue. High demand for planning tools.",
  },
  {
    company_name: "Southern Company",
    account_type: "utility",
    utility_category: "investor-owned",
    website: "southerncompany.com",
    service_territory: "Alabama, Georgia, Mississippi",
    annual_capex: 9500000000,
    num_substations: 620,
    headquarters: "Atlanta, GA",
    priority_score: 92,
    notes: "Strong growth in South. Interconnection pressures.",
  },
  {
    company_name: "Dominion Energy",
    account_type: "utility",
    utility_category: "investor-owned",
    website: "dominionenergy.com",
    service_territory: "Virginia, North Carolina",
    annual_capex: 8500000000,
    num_substations: 580,
    headquarters: "Richmond, VA",
    priority_score: 91,
    notes: "Data center growth corridor. Strategic priority.",
  },
  {
    company_name: "Exelon Corporation",
    account_type: "utility",
    utility_category: "investor-owned",
    website: "exeloncorp.com",
    service_territory: "Illinois, Pennsylvania, New York, California",
    annual_capex: 8000000000,
    num_substations: 550,
    headquarters: "Chicago, IL",
    priority_score: 90,
    notes: "Multi-state operator. ISO-NE connection.",
  },
  {
    company_name: "FirstEnergy Corp",
    account_type: "utility",
    utility_category: "investor-owned",
    website: "firstenergycorp.com",
    service_territory: "Ohio, Pennsylvania, New Jersey, New York",
    annual_capex: 6500000000,
    num_substations: 480,
    headquarters: "Akron, OH",
    priority_score: 89,
    notes: "Dense Northeast utility. High planning complexity.",
  },
  {
    company_name: "Entergy Corporation",
    account_type: "utility",
    utility_category: "investor-owned",
    website: "entergy.com",
    service_territory: "Arkansas, Louisiana, Mississippi, Texas",
    annual_capex: 6000000000,
    num_substations: 420,
    headquarters: "New Orleans, LA",
    priority_score: 88,
    notes: "Southwest utility. Growing data center demand.",
  },
  {
    company_name: "PPL Electric",
    account_type: "utility",
    utility_category: "investor-owned",
    website: "pplelectric.com",
    service_territory: "Pennsylvania, Kentucky",
    annual_capex: 5500000000,
    num_substations: 380,
    headquarters: "Allentown, PA",
    priority_score: 87,
    notes: "Regional utility. Active planning team.",
  },
  {
    company_name: "American Water Works",
    account_type: "utility",
    utility_category: "investor-owned",
    website: "amwater.com",
    service_territory: "16 states",
    annual_capex: 5200000000,
    num_substations: 350,
    headquarters: "Camden, NJ",
    priority_score: 86,
    notes: "Water utility. Different use case but same planning challenges.",
  },

  // ── Top Municipal/Public Utilities ─────────────────────────────────────────

  {
    company_name: "Los Angeles Department of Water and Power",
    account_type: "utility",
    utility_category: "public",
    website: "ladwp.com",
    service_territory: "Los Angeles, CA",
    annual_capex: 3200000000,
    num_substations: 280,
    headquarters: "Los Angeles, CA",
    priority_score: 85,
    notes: "Large public utility. Significant modernization efforts.",
  },
  {
    company_name: "Sacramento Municipal Utility District",
    account_type: "utility",
    utility_category: "public",
    website: "smud.org",
    service_territory: "Sacramento, CA",
    annual_capex: 2100000000,
    num_substations: 180,
    headquarters: "Sacramento, CA",
    priority_score: 84,
    notes: "West Coast utility. Tech-forward organization.",
  },
  {
    company_name: "Austin Energy",
    account_type: "utility",
    utility_category: "public",
    website: "austintexas.gov/austin-energy",
    service_territory: "Austin, TX",
    annual_capex: 1800000000,
    num_substations: 150,
    headquarters: "Austin, TX",
    priority_score: 83,
    notes: "Data center boom in Texas. Growing capacity needs.",
  },

  // ── Cooperatives ───────────────────────────────────────────────────────────

  {
    company_name: "Tri-State Generation and Transmission Association",
    account_type: "utility",
    utility_category: "cooperative",
    website: "tristategt.org",
    service_territory: "Colorado, Nebraska, Wyoming",
    annual_capex: 4200000000,
    num_substations: 320,
    headquarters: "Westminster, CO",
    priority_score: 82,
    notes: "Large cooperative serving 42 members. Wholesale level planning.",
  },

  // ── Data Center Developers (Top 20) ───────────────────────────────────────

  {
    company_name: "Equinix",
    account_type: "developer",
    website: "equinix.com",
    service_territory: "Global (all regions)",
    annual_capex: 4500000000,
    num_substations: 0,
    industry_focus: "Data Center",
    headquarters: "San Jose, CA",
    priority_score: 88,
    notes: "Largest data center operator. Massive interconnection pipeline.",
  },
  {
    company_name: "Digital Realty",
    account_type: "developer",
    website: "digitalrealty.com",
    service_territory: "Global (all regions)",
    annual_capex: 3800000000,
    num_substations: 0,
    industry_focus: "Data Center",
    headquarters: "San Francisco, CA",
    priority_score: 87,
    notes: "Major DC operator. Focus on edge and core.",
  },
  {
    company_name: "CoreWeave (AI Infrastructure)",
    account_type: "developer",
    website: "coreweave.com",
    service_territory: "US (East, West Coast focus)",
    annual_capex: 2500000000,
    num_substations: 0,
    industry_focus: "AI/GPU Data Center",
    headquarters: "San Jose, CA",
    priority_score: 92,
    notes: "Fast-growing AI infrastructure. Massive power needs. PRIORITY.",
  },
  {
    company_name: "Lambda Labs",
    account_type: "developer",
    website: "lambdalabs.com",
    service_territory: "US (multiple regions)",
    annual_capex: 1200000000,
    num_substations: 0,
    industry_focus: "GPU Cloud",
    headquarters: "San Francisco, CA",
    priority_score: 89,
    notes: "AI compute platform. High-density power requirements.",
  },
  {
    company_name: "xAI (Elon Musk)",
    account_type: "developer",
    website: "x.ai",
    service_territory: "Tennessee (primary)",
    annual_capex: 3000000000,
    num_substations: 0,
    industry_focus: "AI Data Center",
    headquarters: "Memphis, TN",
    priority_score: 94,
    notes: "Giga-scale Memphis facility. High-touch opportunity. PRIORITY.",
  },
  {
    company_name: "Crusoe Energy",
    account_type: "developer",
    website: "crusoeenergy.com",
    service_territory: "Texas, Wyoming (stranded power focus)",
    annual_capex: 800000000,
    num_substations: 0,
    industry_focus: "Energy Optimization",
    headquarters: "San Francisco, CA",
    priority_score: 85,
    notes: "Stranded power utilization. Unique use case.",
  },

  // ── Utility Consultants & Integrators ──────────────────────────────────────

  {
    company_name: "McKinsey Power & Utilities",
    account_type: "consultant",
    website: "mckinsey.com/industries/electric-power-and-natural-gas",
    service_territory: "Global",
    annual_capex: 0,
    num_substations: 0,
    industry_focus: "Consulting",
    headquarters: "New York, NY",
    priority_score: 80,
    notes: "Strategic advisor to utilities. Could be partner or channel.",
  },
  {
    company_name: "Deloitte Energy & Resources",
    account_type: "consultant",
    website: "deloitte.com",
    service_territory: "Global",
    annual_capex: 0,
    num_substations: 0,
    industry_focus: "Consulting",
    headquarters: "New York, NY",
    priority_score: 79,
    notes: "Big 4 consulting. Grid modernization focus.",
  },
  {
    company_name: "Accenture Energy",
    account_type: "consultant",
    website: "accenture.com/energy",
    service_territory: "Global",
    annual_capex: 0,
    num_substations: 0,
    industry_focus: "Consulting",
    headquarters: "New York, NY",
    priority_score: 78,
    notes: "Large consulting firm. Digital transformation work.",
  },
  {
    company_name: "Itron (Utilities Software)",
    account_type: "consultant",
    website: "itron.com",
    service_territory: "Global",
    annual_capex: 500000000,
    num_substations: 0,
    industry_focus: "Utility Software",
    headquarters: "Liberty Lake, WA",
    priority_score: 82,
    notes: "Major utility software provider. Could be integration partner or competitor.",
  },
  {
    company_name: "Siemens Grid (Smart Grid Solutions)",
    account_type: "consultant",
    website: "siemens.com",
    service_territory: "Global",
    annual_capex: 800000000,
    num_substations: 0,
    industry_focus: "Grid Technology",
    headquarters: "Erlangen, Germany",
    priority_score: 81,
    notes: "Grid modernization technology leader. Partnership opportunity.",
  },
];

/**
 * Instructions for using this seed data:
 * 1. Run in seeding script during initial setup
 * 2. Each record should be enhanced with:
 *    - Key contact research (LinkedIn scraping)
 *    - Company financials validation
 *    - Planning team size estimation
 * 3. Import into db with:
 *    INSERT INTO target_accounts (columns) VALUES (...)
 */
